### ISSUE TITLE
Did an npm install. It is failing while looking for 'python2'. Any idea?

### ISSUE THREAD

**Issue by abhibt** [joeattardi/github-pr-dashboard#34]
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Abhi\\github-pr-dashboard-master\\github-pr-dashboard-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:158:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Abhi\\github-pr-dashboard-master\\github-pr-dashboard-master\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Abhi\\github-pr-dashboard-master\\github-pr-dashboard-master\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Abhi\\github-pr-dashboard-master\\github-pr-dashboard-master\\node_modules\\which\\which.js:80:29)\n    at C:\\Abhi\\github-pr-dashboard-master\\github-pr-dashboard-master\\node_modules\\which\\which.js:89:16\n    at C:\\Abhi\\github-pr-dashboard-master\\github-pr-dashboard-master\\node_modules\\isexe\\index.js:42:5\n    at C:\\Abhi\\github-pr-dashboard-master\\github-pr-dashboard-master\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python27\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:291:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Abhi\\github-pr-dashboard-master\\github-pr-dashboard-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Abhi\github-pr-dashboard-master\github-pr-dashboard-master\node_modules\node-sass
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abhit\AppData\Roaming\npm-cache\_logs\2019-04-10T09_33_29_242Z-debug.log

**Comment by abhibt** [comment]
Solved by downloading Python 2.7 version.

**Comment by abhibt** [comment]
Compiled and running now.
Visual Studio Express 2019 with C++ compiler needs to be installed can be mentioned as a prerequisite.
